# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistem_programlama_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departmant',
            fields=[
                ('department_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem_programlama_v1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_code', models.TextField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
    ]
